### ISSUE TITLE
bip44 support

### ISSUE THREAD

**Issue by tynes** [Constellation-Labs/constellation#144] opened 2018-08-15 01:41 UTC
Are you planning on adopting multi account hierarchy for deterministic wallets?
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
It appears as if you are using the same cryptography as bitcoin to generate private keys, so it should be possible to integrate into the current ecosystem.

If so, are you planning on registering a purpose field here?
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by tynes** [comment] 2018-08-20 18:53
Hey @Nikolaj-K, yes I am on the discord. I would like to be sure that the merkle tree implementation isn't susceptible to attacks that bitcoin was at one point, there are new blockchain projects coming out that forget the past.  See this library for more information: https://github.com/bitcoinjs/merkle-lib

This issue in particular was raised because [bip32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) private key derivation would greatly increase the usefulness of this protocol for developers, as much of the common private key infrastructure would be able to be applied to the constellation protocol.  You need a [bip44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) coin type to be registered to take advantage of this

**Comment by ryle-goehausen** [comment] 2018-08-22 21:14
Yes absolutely, although that is not as much as a priority as solidifying the core protocol right now. Eventually we want full multi-sig transaction support as well, and possibly support for other signature types (different curves).

**Comment by tynes** [comment] 2018-08-22 21:55
Awesome, thank you for the response. Makes sense to prioritize the core protocol first

**Comment by buckysballs** [comment] 2019-11-07 20:55
Closing as duplicate of #671 at #644

**Closed by buckysballs** 2019-11-07 20:55 UTC
